__title__ = 'volcengine_sdk_rec'
__description__ = 'SDK for volcengine'
__url__ = 'https://github.com/volcengine/volcengine-sdk-python-rec'
__version__ = '1.2.0'
__author__ = 'Lin Gan'
__author_email__ = 'ganlin.coder@bytedance.com'
__license__ = 'Apache 2.0'
__copyright__ = 'Copyright 2022 Bytedance'
