# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: volcengine_rec_sdk_metrics.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n volcengine_rec_sdk_metrics.proto\x12\x1cvolcengine.recommend.metrics\"\xa5\x01\n\x06Metric\x12\x0e\n\x06metric\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x04\x12\r\n\x05value\x18\x03 \x01(\x01\x12<\n\x04tags\x18\x04 \x03(\x0b\x32..volcengine.recommend.metrics.Metric.TagsEntry\x1a+\n\tTagsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"F\n\rMetricMessage\x12\x35\n\x07metrics\x18\x01 \x03(\x0b\x32$.volcengine.recommend.metrics.Metricb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'volcengine_rec_sdk_metrics_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _METRIC_TAGSENTRY._options = None
  _METRIC_TAGSENTRY._serialized_options = b'8\001'
  _METRIC._serialized_start=67
  _METRIC._serialized_end=232
  _METRIC_TAGSENTRY._serialized_start=189
  _METRIC_TAGSENTRY._serialized_end=232
  _METRICMESSAGE._serialized_start=234
  _METRICMESSAGE._serialized_end=304
# @@protoc_insertion_point(module_scope)
